name: Build TBK Mini Firmware

on:
  workflow_dispatch:
    inputs:
      keyboard:
        description: 'Keyboard variant'
        required: true
        default: 'bastardkb/tbkmini/v2/splinky_2'
        type: choice
        options:
          - 'bastardkb/tbkmini/v2/splinky_2'
      keymap:
        description: 'Keymap name'
        required: true
        default: 'gaming_de'
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/qmk/qmk_cli

    steps:
      - name: Disable safe.directory check
        run: |
          git config --global --add safe.directory '*'

      - name: Checkout QMK Firmware
        uses: actions/checkout@v7
        with:
          submodules: recursive

      - name: Install dependencies
        run: pip3 install -r requirements-dev.txt

      - name: Build firmware
        run: qmk compile -kb ${{ inputs.keyboard }} -km ${{ inputs.keymap }}

      - name: Upload firmware
        uses: actions/upload-artifact@v7
        with:
          name: firmware-${{ inputs.keymap }}
          if-no-files-found: ignore
          path: |
            *.bin
            *.hex
            *.uf2
